FROM ruby:3.3.1

# Expose port
EXPOSE 3001

# Install dependencies
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs postgresql-client chromium-driver

# Set app directory
ENV APP_HOME /orca-mais-api-test
RUN mkdir -p ${APP_HOME}
WORKDIR ${APP_HOME}

# Install gems
COPY Gemfile* ./
RUN bundle install

# Copy scripts and grant execute permission
COPY tests/* /usr/bin/
RUN chmod -R +x /usr/bin/*

# Copy app files
COPY . .
