---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/carts":
    get:
      summary: Get current cart
      tags:
      - Carts
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                Default:
                  value:
                    id: 2025
                    products: []
                    total_price: 0.0
    post:
      summary: Create cart
      tags:
      - Carts
      parameters: []
      responses:
        '201':
          description: Successful
          content:
            application/json:
              examples:
                Default:
                  value:
                    id: 2029
                    products:
                    - id: 1132
                      name: Test Product
                      quantity: 2
                      unit_price: 10.0
                      total_price: 20.0
                    total_price: 20.0
        '404':
          description: Product not found
          content:
            application/json:
              examples:
                Default:
                  value:
                    error: Resource not found.
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/v1/carts/requests/create"
  "/carts/add_item":
    post:
      summary: Add quantity to existing item
      tags:
      - Carts
      parameters: []
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                Default:
                  value:
                    id: 2034
                    products:
                    - id: 1135
                      name: Test Product
                      quantity: 2
                      unit_price: 10.0
                      total_price: 20.0
                    total_price: 20.0
        '404':
          description: Product not found
          content:
            application/json:
              examples:
                Default:
                  value:
                    error: Resource not found.
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/v1/carts/requests/add_item"
  "/carts/{product_id}":
    parameters:
    - name: product_id
      in: path
      required: true
      schema:
        type: string
    delete:
      summary: Remove item from cart
      tags:
      - Carts
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                Default:
                  value:
                    id: 2039
                    products: []
                    total_price: 0.0
        '404':
          description: Item not found in cart
          content:
            application/json:
              examples:
                Default:
                  value:
                    error: Produto não encontrado no carrinho.
  "/products":
    get:
      summary: List all products
      tags:
      - Products
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/v1/products/responses/index"
    post:
      summary: Create a new product
      tags:
      - Products
      parameters: []
      responses:
        '201':
          description: Successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/v1/products/responses/create"
        '422':
          description: Validation errors
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/v1/products/requests/create"
  "/products/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
    get:
      summary: Show product
      tags:
      - Products
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/v1/products/responses/show"
        '404':
          description: Not found
    patch:
      summary: Update product
      tags:
      - Products
      parameters: []
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/v1/products/responses/update"
        '422':
          description: Validation errors
        '404':
          description: Not found
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/v1/products/requests/update"
    delete:
      summary: Delete product
      tags:
      - Products
      responses:
        '204':
          description: Successful
        '404':
          description: Not found
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
  schemas:
    _common:
      Error:
        type: object
        properties:
          errors:
            type: object
            additionalProperties:
              type: array
              items:
                type: string
      Pagination:
        type: object
        properties:
          current_page:
            type: integer
          total_pages:
            type: integer
          total_count:
            type: integer
          per_page:
            type: integer
    _private:
      User:
        type: object
        properties:
          id:
            type: integer
          email:
            type: string
          created_at:
            type: string
            format: date-time
          updated_at:
            type: string
            format: date-time
    v1:
      carts:
        _common:
          title: Cart
          type: object
          additionalProperties: true
          properties:
            id:
              type: integer
            total_price:
              type: number
              format: decimal
            products:
              type: array
              items:
                "$ref": "#/components/schemas/v1/products/_common"
        requests:
          add_item:
            title: Add Item to Cart Request
            type: object
            properties:
              cart:
                type: object
                properties:
                  product_id:
                    type: integer
                  quantity:
                    type: integer
                required:
                - product_id
                - quantity
            required:
            - cart
          create:
            title: Create Cart Request
            type: object
            properties:
              cart:
                type: object
                properties:
                  product_id:
                    type: integer
                  quantity:
                    type: integer
                required:
                - product_id
                - quantity
            required:
            - cart
          update:
            update:
              type: object
              properties:
                cart:
                  type: object
                  properties:
                    product_id:
                      type: integer
                    quantity:
                      type: integer
                  required:
                  - product_id
                  - quantity
              required:
              - cart
        responses:
          add_item:
            title: Add Item to Cart Response
            "$ref": "#/components/schemas/v1/carts/_common"
          create:
            title: Create Cart Response
            "$ref": "#/components/schemas/v1/carts/_common"
          remove_item:
            title: Remove Item from Cart Response
            "$ref": "#/components/schemas/v1/carts/_common"
          show:
            title: Show Cart Response
            "$ref": "#/components/schemas/v1/carts/_common"
      products:
        _common:
          title: Product
          type: object
          properties:
            id:
              type: integer
            name:
              type: string
            quantity:
              type: integer
            unit_price:
              type: number
              format: decimal
            total_price:
              type: number
              format: decimal
        requests:
          create:
            create:
              type: object
              properties:
                product:
                  type: object
                  properties:
                    name:
                      type: string
                    price:
                      type: number
                      format: decimal
                  required:
                  - name
                  - price
              required:
              - product
          update:
            update:
              type: object
              properties:
                product:
                  type: object
                  properties:
                    name:
                      type: string
                    price:
                      type: number
                      format: decimal
              required:
              - product
        responses:
          create:
            create:
              "$ref": "#/components/schemas/Product"
          index:
            index:
              type: array
              items:
                "$ref": "#/components/schemas/Product"
          show:
            show:
              "$ref": "#/components/schemas/Product"
          update:
            update:
              "$ref": "#/components/schemas/Product"
servers:
- url: http://localhost:3000
